### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by kirill-dev-pro** [magicismight/static-container#4]
Have no idea what is this error about

```log
● Test suite failed to run

    /my-work-dir/node_modules/static-container/StaticContainer.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React, { Component, Children } from 'react';
                                                                                                    ^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/react-native-root-siblings/index.js:3:1)
```

jest-expo@35.0.0
  └── jest@24.9.0
npm v6.10.0
node v12.7.0

```
"transformIgnorePatterns": [
    "node_modules/(?!static-container)/"
  ],
```
is already added to `package.json`

**Comment by Zmeu213** [comment]
The problem was in `projects`. I've got 2 projects and this is a standalone jest configurations in package.json so `transformIgnorePatterns` should be inside project config like this
```json
"jest": {
    "projects": [
      { 
        "preset": "jest-expo/ios",
        "transformIgnorePatterns": [
          "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base|static-container)"
        ],
        "globals": {
          "__TEST__": true
        }
      },
      { 
        "preset": "jest-expo/android",
        "transformIgnorePatterns": [
          "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base|static-container)"
        ],
        "globals": {
          "__TEST__": true
        }
      }
    ]
  },
```
